schema_version = "1.0.0"

id = "merlin_import_export"
version = "1.0.1"
name = "Merlin Import/Export"
tagline = "Import AutoCAD DXFs with auto scale/position and export mesh edges as a layered DXF"
maintainer = "Calofin"
type = "add-on"
website = "https://github.com/ultrapolar/calofin"
tags = ["Import-Export", "Mesh"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Read imported DXF files and write exported DXF files"
