"""AGENTS.md is a faithful router to the skills it is generated from.

Claude Code finds `.claude/skills/` by itself; every other agent reads
`AGENTS.md` at the repo root.  That makes AGENTS.md a second place the
same facts are written, which in this tree is the shape of a bug --
README.md said the panel covered 62 commands while the panel carried
66, because the number was prose.  So AGENTS.md is generated, and this
holds the generator to three promises:

  * it is CURRENT.  The staleness half is `tools/gen_agents_md.py
    --check`, which `check_standards.py` runs, but a test that fails
    for the same reason says so in the suite rather than only in the
    lint;
  * NOTHING IS SILENTLY DROPPED.  Every skill under `.claude/skills/`
    and every script beside them reaches the router -- a skill added
    and not routed to is a skill non-Claude agents cannot find, and
    nothing else would notice;
  * IT DOES NOT INVENT.  Every path it points at exists, and the
    branch it names is the branch CLAUDE.md pins.

Run: python3 tests/test_agent_docs.py
"""

import os
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "tools"))

import gen_agents_md as gen  # noqa: E402

FAILS = []


def check(label, cond, detail=""):
    if cond:
        print("  ok   %s" % label)
    else:
        print("  FAIL %s%s" % (label, ("  -- " + detail) if detail else ""))
        FAILS.append(label)


# ----------------------------------------------------------------------
print("agent docs -- the router is current")

problems = gen.check()
check("gen_agents_md.check() is clean",
      not problems, "; ".join(problems))

check("AGENTS.md exists at the repo root",
      (ROOT / "AGENTS.md").is_file())

body = (ROOT / "AGENTS.md").read_text(encoding="utf-8")

check("it says it is generated, so nobody hand-edits it",
      "GENERATED by tools/gen_agents_md.py" in body)

# ----------------------------------------------------------------------
print("agent docs -- nothing is silently dropped")

sk = gen.skills()
check("there are skills to route to", bool(sk), repr(sk))

for name, head, path, _refs in sk:
    check("%s is routed to" % name, path in body)
    check("%s has a non-empty headline" % name, bool(head), repr(head))
    # The headline is the description's opening clause; an empty one
    # would render a table row with no task in it.
    check("%s's headline is not the whole description" % name,
          len(head) < 160, repr(head))

for name, _head, _path, refs in sk:
    for r in refs:
        check("%s's reference %s is named" % (name, os.path.basename(r)),
              r in body)

sc = gen.scripts()
check("there are scripts to route to", bool(sc), repr(sc))

for cmd, blurb in sc:
    # The command carries the path; the path is what has to appear.
    path = cmd.split()[1]
    check("%s is routed to" % os.path.basename(path), path in body)
    check("%s has a blurb" % os.path.basename(path), bool(blurb))

# ----------------------------------------------------------------------
print("agent docs -- it does not invent")

# Every repo-relative path the router names must exist.  A router that
# points at a file that is not there is worse than one that says
# nothing: it costs the reader the lookup before it costs them the
# answer.
named = set()
for token in body.replace("`", " ").split():
    t = token.strip("(),;:")
    if t.startswith(".claude/") or t.startswith("tools/") \
            or t.startswith("tests/"):
        named.add(t)
missing = sorted(t for t in named
                 if "<" not in t and not (ROOT / t).exists())
check("every .claude/, tools/ and tests/ path it names exists",
      not missing, repr(missing))

trunk = gen.trunk()
check("the branch it names was read from CLAUDE.md, not typed",
      trunk in body and trunk != "the trunk named in CLAUDE.md", trunk)
check("and CLAUDE.md really pins that branch",
      ("`%s`" % trunk) in (ROOT / "CLAUDE.md").read_text(encoding="utf-8"))

# The seam: only AGENTS.md today, but check()/write() iterate ADAPTERS,
# so an adapter added without a renderer would be a silent no-op.
check("every ADAPTERS entry has a callable renderer",
      all(callable(v) for v in gen.ADAPTERS.values()),
      repr(gen.ADAPTERS))

# ----------------------------------------------------------------------
print()
if FAILS:
    print("test_agent_docs: %d FAILURE(S): %s" % (len(FAILS), ", ".join(FAILS)))
    sys.exit(1)
print("test_agent_docs: all checks passed")
