#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Every SHOP TERM is one knob per tool that writes it, and nothing
writes it around the knob.

A shop term (tools/terms.py) is wording a tool writes INTO THE DRAWING
that the shop may spell its own way -- " Typ.", "Not Given".  It works
only if every tool that writes the wording reads it from its knob: one
site left spelling the literal draws the shipped wording in a shop that
chose another, next to callouts that follow the shop's.  So:

  T1  member     every member knob tools/terms.py names is in its
                 file's tunables block, read through the tool's term
                 reader for THAT term -- (x:term "ID" LIT) -- with LIT
                 the term's default.  In lisp/ and in the shared/parts/
                 twin, where the reader is cal:term.
  T2  join       a tunables knob that SHIPS a term's default but is not
                 a member: it spells the same wording under its own
                 name, and the Terms page cannot reach it.  "join term
                 X" -- read it through the term reader and add it to
                 X's members.
  T3  literal    a term's default spelled as a string anywhere else in
                 a file's CODE (comments are not read) -- outside the
                 tunables block, outside LAZPANEL's generated catalog,
                 and not the fallback of a term-reader call that stands
                 behind its member knob (x:term "ID" LIT, LIT that
                 term's default, in a form that reads one of ID's
                 member knobs -- NORMIESTEP's name-guarded ns-typnote
                 is one; a bare reader call in the knob's place passes
                 a per-tool LAZTUNE value by, so it is a site).  Only
                 the KNOB FORMS of the tunables block are skipped, not
                 a defun that sits inside the block's span.  Drawing
                 text there bypasses the knob.  Prose
                 that legitimately names the wording -- a tutorial
                 sentence, a console line, a report row that describes
                 rather than labels -- is a line in
                 tools/terms_baseline.txt:
                     file|defun|string|reason
                 with the lisp/ path (a twin's finding maps to its
                 source), and a reason.  A line nothing matches any
                 more is STALE and fails too.
  T4  reader     every tool-local term reader is the same six lines
                 but for its prefix, is defined ABOVE the tunables
                 block that calls it, and its tools/mirror_shared.py
                 entry swaps it for cal:term.

Over lisp/ and shared/parts/.

    python3 tools/check_terms.py          # exit 1 on any problem
    python3 tools/check_terms.py --list   # every T3 site, baselined or not
"""

import argparse
import collections
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from callib import LISP_DIR, PARTS_DIR, ROOT, lsp_files, read  # noqa: E402
import knobs  # noqa: E402
import terms as termsmod  # noqa: E402

BASELINE = ROOT / "tools" / "terms_baseline.txt"
PANEL_BEGIN = ";;; >>> lzp:*knobs* -- GENERATED by tools/gen_knobs.py"
PANEL_END = ";;; <<< lzp:*knobs*"

#: the reader every lisp/ copy must be, prefix aside
READER = ('(defun {p}term (id dflt / v)\n'
          '  (setq v (getenv (strcat "CalofinTerm-" id)))\n'
          '  (if (and v (/= v "")) v dflt))')
READER_HEAD = re.compile(r'^\(defun ([a-z0-9]+[:-])term\s', re.M)

#: the text just before a term reader's fallback argument: a string
#: there is the reader's own default, which READS the term, not a site
#: that writes around it -- NORMIESTEP's name-guarded (ns-typnote)
TERM_ARG = re.compile(r'\([a-z0-9]+[:-]term\s+"[a-z0-9-]+"\s+\Z')

Hit = collections.namedtuple("Hit", "file defun string line")


# ------------------------------------------------------------ reading

def lisp_strings(src):
    """[(offset, content)] of every string literal in SRC's code --
    comments skipped."""
    out, i, n = [], 0, len(src)
    while i < n:
        c = src[i]
        if c == ';':
            j = src.find('\n', i)
            i = n if j < 0 else j
        elif c == '"':
            j = i + 1
            buf = []
            while j < n and src[j] != '"':
                if src[j] == '\\' and j + 1 < n:
                    buf.append(src[j:j + 2])
                    j += 2
                else:
                    buf.append(src[j])
                    j += 1
            out.append((i, ''.join(buf)))
            i = j + 1
        else:
            i += 1
    return out


def defun_at(src, off):
    """The name of the top-level defun OFF sits inside, or '<top>'."""
    k = src.rfind('\n(defun ', 0, off + 1)
    if k < 0 and src.startswith('(defun '):
        k = -1
    elif k < 0:
        return '<top>'
    start = k + 1
    end = knobs.sexp_end(src, start)
    if off >= end:
        return '<top>'
    m = re.match(r'\(defun\s+([^\s()]+)', src[start:])
    return m.group(1) if m else '<top>'


def exempt_spans(src):
    """Spans T3 does not read: each KNOB FORM of the tunables block --
    the (setq ...) or guarded (if (not (boundp ...)) (setq ...)) that
    declares a knob -- and LAZPANEL's generated catalog (it transcribes
    the blocks and tools/terms.py).

    Not the whole block: knobs.block_of runs to the block's end line,
    else the next rule, and in a file that has neither for a long way
    (FITABHD's reached 72% of the file, 217 defuns) the "block" is most
    of the code.  A defun inside it is code like any other."""
    spans = []
    block, _ = knobs.block_of(src)
    if block:
        i = src.find(block)
        if i >= 0:
            for off, guarded in knobs.knob_starts(block):
                start = block.rfind('\n(if ', 0, off) + 1 if guarded else off
                spans.append((i + start, i + knobs.sexp_end(block, start)))
    i, j = src.find(PANEL_BEGIN), src.find(PANEL_END)
    if 0 <= i < j:
        spans.append((i, j))
    return spans


def enclosing(src, pos):
    """The text of the form whose open paren most closely encloses POS,
    read from the top-level form POS sits in; '' at top level."""
    k = src.rfind('\n(', 0, pos) + 1
    stack, i = [], k
    while i < pos:
        c = src[i]
        if c == ';':
            j = src.find('\n', i)
            i = pos if j < 0 else j
            continue
        if c == '"':
            i += 1
            while i < pos and src[i] != '"':
                i += 2 if src[i] == '\\' else 1
        elif c == '(':
            stack.append(i)
        elif c == ')' and stack:
            stack.pop()
        i += 1
    if not stack:
        return ''
    return src[stack[-1]:knobs.sexp_end(src, stack[-1])]


def reader_fallback(src, off, s, terms):
    """True when the string at OFF is the fallback of a term-reader call
    that stands BEHIND its member knob: (x:term "ID" LIT) with LIT
    exactly term ID's default, inside a form that also reads one of
    ID's member knobs -- NORMIESTEP's (ns-name *cs-typ-note* (ns-term
    "typ-note" " Typ.")).  A bare reader call in place of the knob
    passes a per-tool LAZTUNE value by, so it is a site like any other."""
    m = TERM_ARG.search(src, max(0, off - 80), off)
    if not m:
        return False
    tid = re.search(r'"([a-z0-9-]+)"', m.group(0)).group(1)
    term = next((t for t in terms if t['id'] == tid), None)
    if term is None or s != term['default']:
        return False
    outer = enclosing(src, m.start())
    call_end = knobs.sexp_end(src, m.start())
    rest = outer.replace(src[m.start():call_end], '', 1)
    return any(re.search(r'(?<![\w:*-])' + re.escape(mem) + r'(?![\w*-])', rest,
                         re.I) for mem in term['members'])


def scan_text(src, relpath, terms=None):
    """T3 hits in one file's text."""
    terms = termsmod.TERMS if terms is None else terms
    spans = exempt_spans(src)
    hits = []
    for off, s in lisp_strings(src):
        if any(a <= off < b for a, b in spans):
            continue
        if reader_fallback(src, off, s, terms):
            continue          # the fallback behind a member knob reads the term
        for t in terms:
            if t['default'] in s:
                hits.append(Hit(relpath, defun_at(src, off), s,
                                src.count('\n', 0, off) + 1))
    return hits


def knob_problems(files, terms=None, member_of=None):
    """T1 and T2 over FILES, {relpath: text}.  A twin (shared/parts/)
    reads its terms through cal:term."""
    terms = termsmod.TERMS if terms is None else terms
    byid = {t['id']: t for t in terms}
    member_of = ({m: t['id'] for t in terms for m in t['members']}
                 if member_of is None else member_of)
    defaults = {t['default']: t['id'] for t in terms}
    found = {}
    problems = []
    for rel, src in sorted(files.items()):
        twin = rel.startswith('shared/')
        for name, raw, _why in knobs.knobs_of_text(src, raw=True):
            tc = knobs.term_call(raw)
            lit = tc[1] if tc else raw
            try:
                val = eval(lit, {}) if lit.startswith('"') else None
            except Exception:                      # noqa: BLE001
                val = None
            if name in member_of:
                tid = member_of[name]
                found.setdefault(name, []).append(rel)
                m = knobs.TERMCALL.match(raw.strip())
                if not m:
                    problems.append(
                        "T1 %s: %s is a member of term %s but ships %s - read "
                        "it through the term reader: (x:term \"%s\" %s)"
                        % (rel, name, tid, raw, tid,
                           '"' + byid[tid]['default'] + '"'))
                    continue
                if twin and m.group(1) != 'cal:':
                    problems.append("T1 %s: %s reads %sterm - the twin's reader "
                                    "is cal:term (the mirror swap is missing)"
                                    % (rel, name, m.group(1)))
                if m.group(2) != tid:
                    problems.append("T1 %s: %s is a member of term %s but reads "
                                    "term %s" % (rel, name, tid, m.group(2)))
                if val != byid[tid]['default']:
                    problems.append("T1 %s: %s ships %s but term %s's default "
                                    "is %r - the two must agree"
                                    % (rel, name, lit, tid, byid[tid]['default']))
            elif isinstance(val, str) and val in defaults:
                problems.append(
                    "T2 %s: %s ships %r, term %s's default - join term %s: "
                    "read it through the term reader and add it to its "
                    "members in tools/terms.py" % (rel, name, val,
                                                   defaults[val], defaults[val]))
    return problems, found


def reader_problems(files, swaps):
    """T4 over FILES, {relpath: text}; SWAPS is {lisp relpath: {local:
    cal}} from the mirror."""
    problems = []
    for rel, src in sorted(files.items()):
        if rel.startswith('shared/'):
            continue
        for m in READER_HEAD.finditer(src):
            p = m.group(1)
            end = knobs.sexp_end(src, m.start())
            if src[m.start():end] != READER.format(p=p):
                problems.append("T4 %s: %sterm is not the reader every tool "
                                "carries - copy it from POOL.LSP's shop "
                                "terms section, prefix changed:\n%s"
                                % (rel, p, READER.format(p=p)))
            block, _ = knobs.block_of(src)
            b = src.find(block) if block else -1
            if b >= 0 and m.start() > b:
                problems.append("T4 %s: %sterm is defined BELOW the tunables "
                                "block that calls it - it is nil while the "
                                "block loads" % (rel, p))
            if swaps.get(rel, {}).get(p + 'term') != 'cal:term':
                problems.append("T4 %s: tools/mirror_shared.py does not swap "
                                "%sterm for cal:term" % (rel, p))
    return problems


# ------------------------------------------------------------ baseline

def load_baseline(path=BASELINE):
    """[(file, defun, string, reason, lineno)] and format problems."""
    rows, problems = [], []
    if not path.exists():
        return rows, problems
    for n, ln in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        if not ln.strip() or ln.lstrip().startswith('#'):
            continue
        parts = ln.split('|', 3)
        if len(parts) != 4 or not parts[3].strip():
            problems.append("%s:%d: not file|defun|string|reason with a "
                            "reason: %r" % (path.name, n, ln))
            continue
        rows.append((parts[0].strip(), parts[1].strip(), parts[2],
                     parts[3].strip(), n))
    return rows, problems


def source_of(rel, twin_src):
    """The lisp/ file a shared/parts/ twin is generated from."""
    return twin_src.get(rel, rel)


def mirror_maps():
    """({twin relpath: lisp relpath}, {lisp relpath: swap map})."""
    import mirror_shared
    twin_src, swaps = {}, {}
    for stem, spec in mirror_shared.TOOLS.items():
        twin_src['shared/parts/%s.lsp' % stem] = spec['src']
        swaps[spec['src']] = spec['swap']
    return twin_src, swaps


def tree_files():
    out = {}
    for d in (LISP_DIR, PARTS_DIR):
        for p in lsp_files(d):
            if 'standards_checker' in p.parts:
                continue
            out[str(p.relative_to(ROOT))] = read(p)
    return out


def run(files=None, baseline=BASELINE, terms=None, twin_src=None, swaps=None):
    """(problems, hits) over the tree (or FILES)."""
    terms = termsmod.TERMS if terms is None else terms
    files = tree_files() if files is None else files
    if twin_src is None or swaps is None:
        twin_src, swaps = mirror_maps()
    problems, found = knob_problems(files, terms)
    for t in terms:
        for m in t['members']:
            if m not in found:
                problems.append("T1 term %s names %s, which no tunables "
                                "block declares" % (t['id'], m))
            else:
                homes = [f for f in found[m] if f.startswith('lisp/')]
                if homes and homes[0] in twin_src.values() and \
                        not any(f.startswith('shared/') for f in found[m]):
                    problems.append("T1 %s: %s has no knob in its "
                                    "shared/parts/ twin" % (homes[0], m))
    problems += reader_problems(files, swaps)
    rows, bproblems = load_baseline(baseline)
    problems += bproblems
    used = set()
    hits = []
    for rel, src in sorted(files.items()):
        for h in scan_text(src, rel, terms):
            key_file = source_of(rel, twin_src)
            match = [r for r in rows
                     if r[0] == key_file and r[1] == h.defun and r[2] == h.string]
            if match:
                used.update(r[4] for r in match)
            else:
                problems.append(
                    "T3 %s:%d (%s): %r spells a shop term's default outside "
                    "the tunables block - use the knob, or if this is prose "
                    "naming the wording add a reasoned line to "
                    "tools/terms_baseline.txt:\n    %s|%s|%s|<why>"
                    % (rel, h.line, h.defun, h.string, key_file, h.defun,
                       h.string))
            hits.append(h)
    for r in rows:
        if r[4] not in used:
            problems.append("%s:%d: stale - nothing spells %r in %s (%s) any "
                            "more; remove the line"
                            % (baseline.name, r[4], r[2], r[0], r[1]))
    return problems, hits


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--list', action='store_true',
                    help='print every T3 site, baselined or not')
    args = ap.parse_args(argv)
    problems, hits = run()
    if args.list:
        for h in hits:
            print("%s:%d %s %r" % (h.file, h.line, h.defun, h.string))
    for p in problems:
        print(p)
    if problems:
        print("check_terms: %d problem(s)" % len(problems))
        return 1
    print("check_terms: %d term(s), %d member knob(s), %d baselined "
          "prose site(s) over lisp/ and shared/parts/, clean"
          % (len(termsmod.TERMS),
             sum(len(t['members']) for t in termsmod.TERMS), len(hits)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
