# SPDX-License-Identifier: GPL-3.0-or-later
"""LAZTUNE's knob catalog, written into LAZPANEL.lsp from every tool's
tunables block.

LAZTUNE lets a drafter set their own value for any knob -- AutoDim's
dimension-style names, POOL's width-to-length ratio, a layer name, a
default -- without editing the file, with the shipped value kept as
"Alec's choice" to come back to.  To offer that it has to know every
knob there is, what it ships as, and what changing it does, and the
one place all three are already written down is each file's own
tunables block (tests/test_tunables.py holds every knob to that block).
So the catalog is TRANSCRIBED from the blocks, never typed: this reads
them through tools/knobs.py and writes ``lzp:*knobs*`` between two
marker lines in lisp/lazpanel/LAZPANEL.lsp, and ``--check`` fails when
what is in the file is not what a fresh run would write -- the same
contract shared/parts/, releases/ and the palette's catalog are held
to (tools/check_standards.py runs it).

The catalog is DATA: ((LABEL FILE (NAME LITERAL MEANING) ...) ...),
every literal as the source text the block spells it in, so the panel
can (read) it back for a type to check a drafter's answer against and
a value to fall back to.  LAZPANEL.lsp stays hand-edited everywhere
else; only the region between the markers is written here, and only
ever whole.
"""

import argparse
import collections
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from callib import ROOT, read  # noqa: E402
import knobs  # noqa: E402
import terms  # noqa: E402

PANEL = ROOT / "lisp" / "lazpanel" / "LAZPANEL.lsp"
BEGIN = ";;; >>> lzp:*knobs* -- GENERATED by tools/gen_knobs.py, do not edit"
END = ";;; <<< lzp:*knobs*"

#: a file whose stem is not the name a drafter knows the tool by.
#: LAZTUNE's dropdown is a list of TOOLS, and a drafter looks for the
#: word they type at the command line -- PERPPTS, not PERP_POINTS.
LABELS = {"check_drawing": "CHECK",
          "perp_points": "PERPPTS",
          "cperp_points": "CPERPPTS"}

#: how much of a knob's explanation the list row carries.  The block's
#: paragraph can run to several sentences; a DCL list row cannot.
MEANING = 110


#: Rules that ARE one decision under two spellings, so no naming rule
#: could pair them.  COVERCHECK carries a PORTED COPY of PADDLE's
#: concave-pad hunt and namespaces its knobs "pad-", so the cap, the
#: pad size and the two angle tolerances read differently in the two
#: files while being the same shop rule with the same shipped value --
#: which is exactly the trio that had to be hand-edited in three files
#: when the cap moved from 4'-6" to 4'-0".  Each entry is a JUDGEMENT
#: that two names mean one thing; the shipped literals still have to
#: agree before they are grouped, so a wrong entry here cannot quietly
#: join two rules that hold different values.
SAME = {"pad-maxrad": "maxrad",
        "pad-size": "padsize",
        "pad-cornertol": "cornertol",
        "pad-arctol": "arctol"}


def words_of(name):
    """NAME's words, lower case, with the pfx: form's prefix off."""
    s = name.strip("*").lower()
    s = re.sub(r"^[a-z0-9]+:\*?", "", s)          # pfx:*name*
    return [p for p in re.split(r"[-_]", s) if p]


def toolword(names):
    """The word every one of a file's knobs starts with, or None.

    The tree spells a knob two ways -- abf:*point-layer*, where the
    tool is the colon prefix, and *PADDLE-MAXRAD*, where it is the
    first word of the name itself.  In the second, that word is the
    tool and not the decision, and leaving it on makes *paddle-maxrad*
    and *mohamaddle-maxrad* look like two rules when they are one."""
    firsts = set()
    for n in names:
        w = words_of(n)
        if len(w) < 2:                     # nothing left if we drop it
            return None
        firsts.add(w[0])
    return firsts.pop() if len(firsts) == 1 else None


def rule_of(name, drop=None):
    """The words of NAME that say WHICH decision it is: the tool's own
    prefix off the front, in whichever of the two spellings it used."""
    w = words_of(name)
    if drop and len(w) > 1 and w[0] == drop:
        w = w[1:]
    if not w:
        return None
    r = "-".join(w)
    return SAME.get(r, r)


def families(cat):
    """[(rule, [name, ...])] -- one shop decision carried by more than
    one tool, each under its own name.

    A shop that puts its survey points on a layer of its own has to say
    so in TWELVE tools, because every tool that reads those points
    carries its own *point-layer*; the pad cap PADDLE, MOHAMADDLE and
    COVERCHECK share is three.  Nothing about that is wrong -- a
    lisp/ file is self-contained on purpose and may not read another
    tool's global -- but it means one decision is twelve edits, and a
    drafter who changes some and not the others gets two tools
    disagreeing about the same drawing.  So LAZTUNE offers to set them
    together, and this is the table it reads.

    Same rule words AND the same shipped literal, in two or more FILES:
    the shared value is what says these really are one decision rather
    than a coincidence of naming."""
    # A SHOP TERM (tools/terms.py) is one decision by declaration: its
    # members are the family, first, whatever their names say -- and a
    # member is in no naming-rule family besides, so "Set everywhere"
    # on it reaches exactly the term's knobs.  Only members the catalog
    # really has are listed; check_terms.py names a missing one.
    have = {name for _rel, ks in cat for name, _l, _w in ks}
    out = []
    taken = set()
    for t in terms.TERMS:
        members = [m for m in t['members'] if m in have]
        taken.update(t['members'])
        if len(members) > 1:
            out.append(("term:" + t['id'], members))
    by = collections.defaultdict(list)
    for relpath, ks in cat:
        drop = toolword([n for n, _l, _w in ks])
        for name, lit, _why in ks:
            if name in taken:
                continue
            rule = rule_of(name, drop)
            if rule:
                by[(rule, lit)].append((relpath, name))
    for (rule, _lit), members in sorted(by.items()):
        if len(set(f for f, _ in members)) < 2:
            continue
        out.append((rule, [n for _, n in members]))
    return out


def lisp_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def label_of(relpath):
    stem = pathlib.Path(relpath).stem
    return LABELS.get(stem, stem.upper())


def region():
    """The text between the markers, markers excluded, freshly built."""
    out = ["(setq lzp:*knobs*", "  '("]
    first = True
    for relpath, ks in knobs.catalog():
        head = "%s(%s %s" % ("" if first else "    ", lisp_str(label_of(relpath)),
                             lisp_str(relpath))
        if first:
            head = "    " + head.lstrip()
        first = False
        out.append(head)
        for name, lit, why in ks:
            why = " ".join(why.split())
            if len(why) > MEANING:
                why = why[:MEANING - 3].rstrip() + "..."
            out.append("     (%s %s %s)" % (lisp_str(name), lisp_str(lit),
                                            lisp_str(why)))
        out[-1] = out[-1] + ")"
    out.append("   ))")
    fams = families(knobs.catalog())
    out.append("")
    out.append(";; One shop decision, and every knob that spells it.  See")
    out.append(";; tools/gen_knobs.py families() for what makes two knobs one")
    out.append(";; decision; LAZTUNE's \"Set everywhere\" writes the lot.")
    out.append("(setq lzp:*knobfam*")
    out.append("  '(")
    for rule, names in fams:
        out.append("    (%s (%s))" % (lisp_str(rule),
                                      " ".join(lisp_str(n) for n in names)))
    out.append("   ))")
    out.append("")
    out.append(";; The SHOP TERMS: drawing text a shop may spell its own way, from")
    out.append(";; tools/terms.py -- (ID DEFAULT MEANING (MEMBER-KNOB ...)).  LAZTUNE's")
    out.append(";; Terms page lists these and writes CalofinTerm-<ID>.")
    out.append("(setq lzp:*terms*")
    out.append("  '(")
    for t in terms.TERMS:
        out.append("    (%s %s %s" % (lisp_str(t['id']), lisp_str(t['default']),
                                      lisp_str(t['meaning'])))
        out.append("     (%s))" % " ".join(lisp_str(m) for m in t['members']))
    out.append("   ))")
    return "\n".join(out) + "\n"


def split(src):
    """(before, current region, after) of PANEL's text, or None when a
    marker is missing."""
    i = src.find(BEGIN)
    j = src.find(END)
    if i < 0 or j < 0 or j < i:
        return None
    i += len(BEGIN) + 1
    return src[:i], src[i:j], src[j:]


def check():
    """Problems as a list of strings, empty when the file is current."""
    src = read(PANEL)
    parts = split(src)
    if parts is None:
        return ["%s: the lzp:*knobs* markers are missing - the catalog "
                "has nowhere to go" % PANEL.relative_to(ROOT)]
    if parts[1] != region():
        return ["%s: lzp:*knobs* is stale - it is not what "
                "tools/gen_knobs.py would write now (a tunables block "
                "changed).  Regenerate: python3 tools/gen_knobs.py"
                % PANEL.relative_to(ROOT)]
    return []


def write():
    src = read(PANEL)
    parts = split(src)
    if parts is None:
        raise SystemExit("gen_knobs: markers missing in %s" % PANEL)
    new = parts[0] + region() + parts[2]
    changed = new != src
    if changed:
        PANEL.write_text(new, encoding="utf-8")
    return changed


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="report staleness instead of writing")
    args = ap.parse_args(argv)
    cat = knobs.catalog()
    n = sum(len(ks) for _, ks in cat)
    if args.check:
        problems = check()
        for p in problems:
            print(p)
        if problems:
            return 1
        print("gen_knobs: lzp:*knobs* current, %d knobs over %d files"
              % (n, len(cat)))
        return 0
    changed = write()
    print("gen_knobs: %s lzp:*knobs* in %s, %d knobs over %d files"
          % ("wrote" if changed else "unchanged", PANEL.relative_to(ROOT),
             n, len(cat)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
