# SPDX-License-Identifier: GPL-3.0-or-later
"""LAZTUNE's knob catalog, written into LAZPANEL.lsp from every tool's
tunables block.

LAZTUNE lets a drafter set their own value for any knob -- AutoDim's
dimension-style names, POOL's width-to-length ratio, a layer name, a
default -- without editing the file, with the shipped value kept as
"Alec's choice" to come back to.  To offer that it has to know every
knob there is, what it ships as, and what changing it does, and the
one place all three are already written down is each file's own
tunables block (tests/test_tunables.py holds every knob to that block).
So the catalog is TRANSCRIBED from the blocks, never typed: this reads
them through tools/knobs.py and writes ``lzp:*knobs*`` between two
marker lines in lisp/lazpanel/LAZPANEL.lsp, and ``--check`` fails when
what is in the file is not what a fresh run would write -- the same
contract shared/parts/, releases/ and the palette's catalog are held
to (tools/check_standards.py runs it).

The catalog is DATA: ((LABEL FILE (NAME LITERAL MEANING) ...) ...),
every literal as the source text the block spells it in, so the panel
can (read) it back for a type to check a drafter's answer against and
a value to fall back to.  LAZPANEL.lsp stays hand-edited everywhere
else; only the region between the markers is written here, and only
ever whole.
"""

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from callib import ROOT, read  # noqa: E402
import knobs  # noqa: E402

PANEL = ROOT / "lisp" / "lazpanel" / "LAZPANEL.lsp"
BEGIN = ";;; >>> lzp:*knobs* -- GENERATED by tools/gen_knobs.py, do not edit"
END = ";;; <<< lzp:*knobs*"

#: a file whose stem is not the name a drafter knows the tool by
LABELS = {"check_drawing": "CHECK"}

#: how much of a knob's explanation the list row carries.  The block's
#: paragraph can run to several sentences; a DCL list row cannot.
MEANING = 110


def lisp_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def label_of(relpath):
    stem = pathlib.Path(relpath).stem
    return LABELS.get(stem, stem.upper())


def region():
    """The text between the markers, markers excluded, freshly built."""
    out = ["(setq lzp:*knobs*", "  '("]
    first = True
    for relpath, ks in knobs.catalog():
        head = "%s(%s %s" % ("" if first else "    ", lisp_str(label_of(relpath)),
                             lisp_str(relpath))
        if first:
            head = "    " + head.lstrip()
        first = False
        out.append(head)
        for name, lit, why in ks:
            why = " ".join(why.split())
            if len(why) > MEANING:
                why = why[:MEANING - 3].rstrip() + "..."
            out.append("     (%s %s %s)" % (lisp_str(name), lisp_str(lit),
                                            lisp_str(why)))
        out[-1] = out[-1] + ")"
    out.append("   ))")
    return "\n".join(out) + "\n"


def split(src):
    """(before, current region, after) of PANEL's text, or None when a
    marker is missing."""
    i = src.find(BEGIN)
    j = src.find(END)
    if i < 0 or j < 0 or j < i:
        return None
    i += len(BEGIN) + 1
    return src[:i], src[i:j], src[j:]


def check():
    """Problems as a list of strings, empty when the file is current."""
    src = read(PANEL)
    parts = split(src)
    if parts is None:
        return ["%s: the lzp:*knobs* markers are missing - the catalog "
                "has nowhere to go" % PANEL.relative_to(ROOT)]
    if parts[1] != region():
        return ["%s: lzp:*knobs* is stale - it is not what "
                "tools/gen_knobs.py would write now (a tunables block "
                "changed).  Regenerate: python3 tools/gen_knobs.py"
                % PANEL.relative_to(ROOT)]
    return []


def write():
    src = read(PANEL)
    parts = split(src)
    if parts is None:
        raise SystemExit("gen_knobs: markers missing in %s" % PANEL)
    new = parts[0] + region() + parts[2]
    changed = new != src
    if changed:
        PANEL.write_text(new, encoding="utf-8")
    return changed


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="report staleness instead of writing")
    args = ap.parse_args(argv)
    cat = knobs.catalog()
    n = sum(len(ks) for _, ks in cat)
    if args.check:
        problems = check()
        for p in problems:
            print(p)
        if problems:
            return 1
        print("gen_knobs: lzp:*knobs* current, %d knobs over %d files"
              % (n, len(cat)))
        return 0
    changed = write()
    print("gen_knobs: %s lzp:*knobs* in %s, %d knobs over %d files"
          % ("wrote" if changed else "unchanged", PANEL.relative_to(ROOT),
             n, len(cat)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
